development:
  adapter: postgresql
  encoding: unicode
  database: nitrous
  pool: 5
  host: localhost
  username: nitrous
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: nitrous
  pool: 5
  host: localhost
  username: nitrous
  password: 